In [1]:
import numpy as np

In [2]:
a = [1, 2, 3, 3]
b = [5, 1, 2, 6]

def jumlah(a, b):
    c = [0] * len(a)
    for i in range(len(a)):
        c[i] = a[i] + b[i]
    return c

In [3]:
a = [1,2,3,4]
b = [6,4,2,7]
np_a = np.array(a)
np_b = np.array(b)

In [4]:
a+b

[1, 2, 3, 4, 6, 4, 2, 7]

In [6]:
np_a +np_b

array([ 7,  6,  5, 11])

In [7]:
np_a *np_b

array([ 6,  8,  6, 28])

In [8]:
# CEK PERFORMA
a = [1] * 1000
b = [2] * 1000

In [9]:
%timeit jumlah(a,b)

172 µs ± 4.46 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
np_a = np.array(a)
np_b = np.array(b)

%timeit np_a + np_b

2.53 µs ± 40.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
# contoh array

a1d = [1,2,3,4,5]
a1d = np.array(a1d)
a1d

array([1, 2, 3, 4, 5])

In [12]:
a2d = [[1,3],[5,4],[7,8]]
a2d = np.array(a2d)
a2d

array([[1, 3],
       [5, 4],
       [7, 8]])

In [13]:
a2d = [[1,3],[5,4,5],[7,8]]
a2d = np.array(a2d)
a2d

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


array([list([1, 3]), list([5, 4, 5]), list([7, 8])], dtype=object)

In [14]:
a = [1,2,3,4,5.4, 'a']
a

[1, 2, 3, 4, 5.4, 'a']

In [15]:
a = np.array(a)
a

array(['1', '2', '3', '4', '5.4', 'a'], dtype='<U32')

In [16]:
A = [[1,3],[5,4],[7,8]]
A = np.array(A)
A

array([[1, 3],
       [5, 4],
       [7, 8]])

In [17]:
A[2][1]

8

In [18]:
A[2,1]

8

In [19]:
# memanggil baris
A[1]

array([5, 4])

In [20]:
A[1, :]

array([5, 4])

In [21]:
# memanggil kolom
A[:, 0]

array([1, 5, 7])

In [22]:
# special array
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.arange(1,6, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [27]:
np.linspace(1, 10, 1200)

array([ 1.        ,  1.00750626,  1.01501251, ...,  9.98498749,
        9.99249374, 10.        ])

In [28]:
A = [[1,3],[5,4],[7,8]]
A = np.array(A)
A

array([[1, 3],
       [5, 4],
       [7, 8]])

In [29]:
A.ndim

2

In [30]:
A.shape

(3, 2)

In [31]:
A.size

6

In [32]:
a = [2,3,1,6,5,7,5,6]
a = np.array(a)
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [33]:

a.reshape((2,4))

array([[2, 3, 1, 6],
       [5, 7, 5, 6]])

In [34]:
a.reshape((2,4)).T

array([[2, 5],
       [3, 7],
       [1, 5],
       [6, 6]])

In [35]:

a.reshape((4,2))

array([[2, 3],
       [1, 6],
       [5, 7],
       [5, 6]])

In [36]:
a = [2,3,1,6,5,7,5,6]
a = np.array(a)
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [37]:

a[np.newaxis]

array([[2, 3, 1, 6, 5, 7, 5, 6]])

In [38]:
a[:,np.newaxis]

array([[2],
       [3],
       [1],
       [6],
       [5],
       [7],
       [5],
       [6]])

In [39]:
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [40]:
np.expand_dims(a, axis=1).shape

(8, 1)

In [41]:
a.shape

(8,)

In [42]:
mat = [[5,4,3,8,2], [4,6,3,7,4], [1,6,4,5,6]]
mat = np.array(mat)
mat

array([[5, 4, 3, 8, 2],
       [4, 6, 3, 7, 4],
       [1, 6, 4, 5, 6]])

In [43]:
mat[1:2, -2:]

array([[7, 4]])

In [44]:
mat > 4

array([[ True, False, False,  True, False],
       [False,  True, False,  True, False],
       [False,  True, False,  True,  True]])

In [45]:
mat[mat > 4]

array([5, 8, 6, 7, 6, 5, 6])

In [46]:

mahasiswa = np.array(['Afif', 'Fahmi', 'Danu', 'Raka'])
nilai = np.array([98.7, 75.3, 53.4, 45.2])

In [47]:
nilai < 60

array([False, False,  True,  True])

In [48]:
kondisi = nilai < 60
mahasiswa[kondisi]

array(['Danu', 'Raka'], dtype='<U5')

In [49]:
A = np.array([[1,2], [3,4]])
B = np.array([[6,5], [2,7]])
c = np.array([1,2])

In [50]:
A

array([[1, 2],
       [3, 4]])

In [52]:
B

array([[6, 5],
       [2, 7]])

In [53]:
A+B

array([[ 7,  7],
       [ 5, 11]])

In [54]:
A/B

array([[0.16666667, 0.4       ],
       [1.5       , 0.57142857]])

In [55]:
A%B

array([[1, 2],
       [1, 4]], dtype=int32)

In [56]:
A.mean(axis=0)

array([2., 3.])

In [57]:
np.random.random((2,3))

array([[0.95586113, 0.76201675, 0.13511936],
       [0.18710168, 0.94620647, 0.85611252]])

In [58]:
C = np.arange(0,12)
C = C.reshape((4,3))

In [59]:
C

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [60]:
C.reshape((5,2))

ValueError: cannot reshape array of size 12 into shape (5,2)